### ISSUE TITLE
Auto resizing of code block is not working in uncover theme

### ISSUE THREAD

**Issue by SmallNibbler** [marp-team/marp-vscode#326] opened 2022-01-27 19:26 UTC
### Version of Marp Tool

Marp for VS Code v1.4.7

### Operating System

Linux

### Environment

Operating System: Manjaro Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.16-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Pentium® CPU 3825U @ 1.90GHz
Memory: 7.7 ГиБ of RAM
Graphics Processor: Mesa Intel® HD Graphics

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.16-1-MANJARO snap

### How to reproduce

1. Set theme: uncover
2. Create code block with code line length bigger then slide width.

### Expected behavior

Auto resizing of code block.

### Actual behavior

Code block is going beyond the slide border.

### Additional information

This behavior has only been seen with the theme uncovered.
![1](https://user-images.githubusercontent.com/14197065/151429177-8baa6498-a09d-4937-87c1-01392096273b.png)

**Comment by yhatt** [comment] 2022-01-27 23:54
It's a known restriction for `uncover` theme in Marp Core v2, not a bug.

> `uncover` theme has disabled code block scaling because we use elastic style that has not compatible with it.
>
> -- [marp-team/marp-core at v2-stable](https://github.com/marp-team/marp-core/tree/v2-stable#:~:text=uncover%20theme%20has%20disabled%20code%20block%20scaling%20because%20we%20use%20elastic%20style%20that%20has%20not%20compatible%20with%20it.e)

This restriction has been already fixed in upcoming [Marp Core v3](https://github.com/marp-team/marp-core/releases/tag/v3.0.0) (https://github.com/marp-team/marp-core/pull/263). Currently Marp for VS Code is sticking to Marp Core v2 due to avoiding breaking changes to exist slides. If a new (pre-release) version that has bundled v3 to the extension was shipped by #318, you would be able to preview auto-scaled code block in `uncover` theme.

**Closed** 2022-01-28 17:16 UTC
