### ISSUE TITLE
Unable to install your extension in Codium

### ISSUE THREAD

**Issue by JOduMonT** [marp-team/marp-vscode#169] opened 2020-09-17 00:54 UTC
Hi;
I would like to use your Marp-VSCode in Codium (a fork of Code) but it is not working

`ext install marp-team.marp-vscode` is not found

**Comment by yhatt** [comment] 2020-09-17 00:58
Duplicate of VSCodium/vscodium#439?

**Closed** 2020-09-23 12:14 UTC

**Comment by MSSandroid** [comment] 2020-09-30 08:30
So marp has no intention to publish the extension on open-vsx.org?

**Comment by yhatt** [comment] 2020-10-01 20:32
@MSSandroid Please open new issue to request. We would work for (automated) publishing to open-vsx if we confirmed it's in demand.
