### ISSUE TITLE
Cannot open preview in vscodium

### ISSUE THREAD

**Issue by elpaso** [marp-team/marp-vscode#179] opened 2020-10-21 08:07 UTC
Hi,

I manually installed marp-team.marp-vscode-0.16.0.vsix in vscodium, the blue icon shows up and export works but I cannot open the preview after choosing "Toggle Marp Preview for current markdown".

Nothing happens and there are no errors or warnings that I can see.

**Comment by yhatt** [comment] 2020-10-21 09:42
Duplicate of #77. "Toggle Marp Preview for current markdown" command is just for toggle the preview mode (regular Markdown or Marp Markdown). It's not meaning open and hide the preview panel.

![](https://raw.githubusercontent.com/marp-team/marp-vscode/master/docs/toggle.gif)

To open the preview panel, you should hit <kbd>Ctrl(Cmd)+Shift+V</kbd> or click ![](https://raw.githubusercontent.com/microsoft/vscode-codicons/master/src/icons/open-preview.svg?sanitize=1) right next to Marp icon.

**Closed by yhatt** 2020-10-21 09:42 UTC

**Comment by elpaso** [comment] 2020-10-21 09:50
@yhatt oh, sorry: stupid me.

Thanks for helping.

**Comment by noraj** [comment] 2022-03-09 11:02
Just for info, marp slides preview won't work with [markdown-preview-enhanced](https://open-vsx.org/extension/shd101wyy/markdown-preview-enhanced) extension. But in newer releases of markdown-preview-enhanced, it hides the default vscode preview button.

![image](https://user-images.githubusercontent.com/16578570/157428861-b1bf6439-1472-47d1-ae3b-80fc798f6459.png)

```json
"markdown-preview-enhanced.hideDefaultVSCodeMarkdownPreviewButtons": false
```

**Comment by RussQuan** [comment] 2023-01-31 02:27
2023.01.31

If someone has the same problem, disabling this extension may work!

<img width="693" alt="image" src="https://user-images.githubusercontent.com/38601123/215645578-7a01867d-1274-400d-9ba9-0550ceea31ab.png">
