### ISSUE TITLE
Custom engine

### ISSUE THREAD

**Issue by xneomac** [marp-team/marp-vscode#86] opened 2019-10-19 15:54 UTC
Is there any way to change the engine used by _marp-vscode_ ? Like in _marp-cli_ when we run the command `marp --engine ./engine.js content.md`.

**Comment by yhatt** [comment] 2019-10-19 19:50
Duplicate of #85. See details in https://github.com/marp-team/marp-vscode/issues/85#issuecomment-543798586.

**Closed by yhatt** 2019-10-19 19:50 UTC
