### ISSUE TITLE
export html linux (.deb) version do not show bg images

### ISSUE THREAD

**Issue by spideryzarc** [marp-team/marp-vscode#467] opened 2024-11-01 13:20 UTC
The preview below displays perfectly, but when exported to HTML, the background image is missing (even in local exports). The same .md file exports correctly on the Windows version. 

Additional Information:

VSCode Version: code_1.95.1-1730355339_amd64.deb
Linux Distribution: KDE Neon 6.2 (fully updated)
Image Path: Verified as correct

[test.md](https://github.com/user-attachments/files/17599961/test.md)
[test.html.txt](https://github.com/user-attachments/files/17599979/test.html.txt)

**Comment by yhatt** [comment] 2024-11-01 14:08
The exported HTML preserves the Markdown specify image path `images/knapsack.jpeg`. Web browser will resolve the image path from the location of file when browsing HTML, so you should export HTML to the correct location.

```
.
├── images/
│   └── knapsack.jpeg
├── test.md
└── test.html
```

If the image location is already confirmed as correct, check your browser's restrictions for HTML location. For example, if your KDE is working on Ubuntu, installed browsers may be [a snap app](https://snapcraft.io/). Because of security, some browsers restrict reading resources from local (`file:///`).
https://askubuntu.com/questions/1435757/firefox-cant-open-files

**Comment by spideryzarc** [comment] 2024-11-03 16:28
Thank you for your attention, @yhatt.

This isn’t an issue with an incorrect image path or browser permissions. I’ve tested in different browsers with the same result, and even uploaded the export to GitHub Pages, where the image still doesn’t display. 

However, when I export using the Windows version, everything works as expected—both locally and on GitHub Pages. 

Thanks again for your help!

**Comment by yhatt** [comment] 2024-11-03 19:09
If the browser is unable to display images, there should be some kind of error output on the browser. Open the browser’s developer tools, go to the Network tab, and check why the image resources are failing to load.

If possible, sharing a minimal reproducible example on GitHub Pages could help in identifying the cause of the issue.

**Comment by yhatt** [comment] 2024-12-01 12:53
The underlying issue may not yet be resolved, but since there have been no extra reports of this problem, we close this issue. We will consider that there is no issue with Marp itself.

If the issue still persists, please feel free to re-open the issue with the requested additional information.

**Closed by yhatt** 2024-12-01 12:53 UTC
Labels: need more info
